1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [1]:
import pandas as pd 
import numpy as np
from copy import deepcopy

pd.Series(list(range(0,10)), name= 'nSeries')


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: nSeries, dtype: int64

2. Write a Pandas program to convert a Panda module Series to Python list and it's type

In [2]:
pd.Series(list(range(0,10)), name= 'nSeries').to_list()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [3]:
a = pd.Series([2, 4, 6, 8, 10]) + pd.Series([1, 3, 5, 7, 9])
b = pd.Series([2, 4, 6, 8, 10]) - pd.Series([1, 3, 5, 7, 9])
c = pd.Series([2, 4, 6, 8, 10]) * pd.Series([1, 3, 5, 7, 9])
d = pd.Series([2, 4, 6, 8, 10]) / pd.Series([1, 3, 5, 7, 9])

print(a,b,c,d)

0     3
1     7
2    11
3    15
4    19
dtype: int64 0    1
1    1
2    1
3    1
4    1
dtype: int64 0     2
1    12
2    30
3    56
4    90
dtype: int64 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [4]:
a = pd.Series([2, 4, 6, 8, 10])
b = pd.Series([1, 3, 5, 7, 9])
print(a == b)
print(a > b)
print(a < b)
print(a != b)

0    False
1    False
2    False
3    False
4    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool


Write a Pandas program to convert a dictionary to a Pandas series.

''' Sample Series: 
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64
''' 



In [5]:
pd.Series({'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})

a    100
b    200
c    300
d    400
e    800
dtype: int64

6. Write a Pandas program to convert a NumPy array to a Pandas series.

{{Sample Series: 
  NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64 
}}

In [6]:
pd.Series(np.array([10, 20, 30, 40, 50]))

0    10
1    20
2    30
3    40
4    50
dtype: int32

Write a Pandas program to change the data type of given a column or a Series.

In [7]:
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
s1.dtype
s2 = pd.to_numeric(s1, errors='coerce')
s2

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

10. Write a Pandas program to convert Series of lists to one Series.

In [8]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])

s.apply(pd.Series).stack().reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

12. Write a Pandas program to add some data to an existing Series.

In [9]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
pd.concat([s,pd.Series(['500', 'PHP'])])

0       100
1       200
2    python
3    300.12
4       400
0       500
1       PHP
dtype: object

13. Write a Pandas program to create a subset of a given series based on value and condition.

In [10]:
s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])

s = s[s<6]
s

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

14. Write a Pandas program to change the order of index of a given series.

In [11]:
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
s
s.reindex(index=['B','A', 'C', 'D', 'E'])

B    2
A    1
C    3
D    4
E    5
dtype: int64

15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [12]:
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
s
print('mean:', s.mean(), '\n std:', s.std())

mean: 4.818181818181818 
 std: 2.522624895547565


16. Write a Pandas program to get the items of a given series not present in another given series.

In [13]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

sr1[~sr1.isin(sr2)]

0    1
2    3
4    5
dtype: int64

17. Write a Pandas program to get the items which are not common of two given series.

In [14]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

sr11 = pd.Series(np.union1d(sr1, sr2))
sr22 = pd.Series(np.intersect1d(sr1, sr2))

sr11[~ sr11.isin(sr22)]

0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64

18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [15]:
num_series = pd.Series(np.random.RandomState(100).normal(10, 4, 20))
np.percentile(num_series,[0, 25, 50, 75, 100])

array([ 3.00093811,  8.09463867, 10.23353705, 12.21537733, 14.61214321])

19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.

In [16]:
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
num_series.value_counts()

5    7
3    7
1    6
2    4
9    4
6    3
8    3
4    3
7    2
0    1
Name: count, dtype: int64

20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.


In [17]:
num_series = pd.Series(np.random.randint(1, 5, [15]))
num_series1 = deepcopy(num_series)
num_series[~ (num_series == num_series.value_counts().index[0])] = 'others'
num_series

C:\Users\1015894\AppData\Local\Temp\ipykernel_20968\4033178407.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'others' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  num_series[~ (num_series == num_series.value_counts().index[0])] = 'others'


0          3
1          3
2          3
3          3
4     others
5     others
6     others
7     others
8          3
9     others
10    others
11         3
12    others
13         3
14    others
dtype: object

In [18]:
num_series1[~num_series1.isin(num_series1.value_counts().index[:1])] = 'Other'
num_series1

C:\Users\1015894\AppData\Local\Temp\ipykernel_20968\11584179.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Other' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  num_series1[~num_series1.isin(num_series1.value_counts().index[:1])] = 'Other'


0         3
1         3
2         3
3         3
4     Other
5     Other
6     Other
7     Other
8         3
9     Other
10    Other
11        3
12    Other
13        3
14    Other
dtype: object

21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

In [19]:
num_series = pd.Series(np.random.randint(1, 10, 9))
num_series[num_series % 5 == 0]

1    5
dtype: int32

22. Write a Pandas program to extract items at given positions of a given series.

In [20]:
num_series = pd.Series(list('2390238923902390239023'))
element_pos = [0, 2, 6, 11, 21]
num_series[element_pos]

0     2
2     9
6     8
11    0
21    3
dtype: object

23. Write a Pandas program to get the positions of items of a given series in another given series.

In [21]:
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
[pd.Index(series1).get_loc(i) for i in series2]

[0, 2, 4, 6, 9]

24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

In [22]:
series1 = pd.Series(['php', 'python', 'java', 'c#'])
series1.apply(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

25. Write a Pandas program to calculate the number of characters in each word in a given series

In [23]:
series1 = pd.Series(['Php', 'Python', 'Java', 'C#'])
series1.apply(lambda x: len(x))

0    3
1    6
2    4
3    2
dtype: int64

26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

In [24]:
series1 = pd.Series([1, 3, 5, 8, 10, 11, 15])
series1.diff()

0    NaN
1    2.0
2    2.0
3    3.0
4    2.0
5    1.0
6    4.0
dtype: float64

27. Write a Pandas program to convert a series of date strings to a timeseries.

In [25]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
pd.to_datetime(date_series, errors='coerce')

0   2015-01-01
1          NaT
2          NaT
3          NaT
4          NaT
5          NaT
dtype: datetime64[ns]

29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

In [26]:
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
pd.to_datetime(date_series.apply(lambda x: '11' + x))

0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

30. Write a Pandas program to filter words from a given series that contain atleast two vowels.

In [27]:
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)


0    False
1     True
2     True
3    False
4     True
5     True
dtype: bool

31. Write a Pandas program to compute the Euclidean distance between two given series.
Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm.

In [31]:
x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])

np.linalg.norm(x-y)

16.492422502470642

32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

In [59]:
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
tem = np.diff(np.sign(np.diff(nums)))
np.where(tem == -2)[0] +1

array([1, 4, 8], dtype=int64)

33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character.

In [80]:
str1 = 'abc def abcdef icd'
ser = pd.Series(list(str1))
element_freq = ser.value_counts()
cf = element_freq.dropna().index[-1]

''.join(ser.replace(" ", cf))

'abcidefiabcdefiicd'

34. Write a Pandas program to compute the autocorrelations of a given numeric series.
From Wikipedia:
Autocorrelation, also known as serial correlation, is the correlation of a signal with a delayed copy of itself as a function of delay. Informally, it is the similarity between observations as a function of the time lag between them.

In [111]:
num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
[num_series.autocorr(i).round(2) for i in range(11)]

[1.0, -0.11, -0.18, 0.22, -0.05, 0.5, -0.33, -0.41, 0.57, 0.01, 0.46]

35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

In [118]:
pd.date_range('2020-01-01', '2020-12-31', freq='W-SUN')

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02', '2020-02-09', '2020-02-16', '2020-02-23',
               '2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22',
               '2020-03-29', '2020-04-05', '2020-04-12', '2020-04-19',
               '2020-04-26', '2020-05-03', '2020-05-10', '2020-05-17',
               '2020-05-24', '2020-05-31', '2020-06-07', '2020-06-14',
               '2020-06-21', '2020-06-28', '2020-07-05', '2020-07-12',
               '2020-07-19', '2020-07-26', '2020-08-02', '2020-08-09',
               '2020-08-16', '2020-08-23', '2020-08-30', '2020-09-06',
               '2020-09-13', '2020-09-20', '2020-09-27', '2020-10-04',
               '2020-10-11', '2020-10-18', '2020-10-25', '2020-11-01',
               '2020-11-08', '2020-11-15', '2020-11-22', '2020-11-29',
               '2020-12-06', '2020-12-13', '2020-12-20', '2020-12-27'],
              dtype='datetime64[ns]', freq='W-SUN')

36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

In [129]:
char_list = list('ABCDEFGHIJKLMNOP')
num_arr = np.arange(8)
num_dict = dict(zip(char_list, num_arr))
num_series = pd.Series(num_dict)
num_series.to_frame().reset_index()

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4
5     F  5
6     G  6
7     H  7

37. Write a Pandas program to stack two given series vertically and horizontally.

In [137]:
series1 = pd.Series(range(10))
series2 = pd.Series(list('pqrstuvwxy'))

# series1.append(series2)
pd.concat([series1, series2])

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

38. Write a Pandas program to check the equality of two given series.

In [141]:
nums1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

nums1 == nums2

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.


In [148]:
nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print(nums.idxmin(),
nums.idxmax())

9 4


40. Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.

In [156]:
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) 

df_data.ne(sr_data, axis=0)

W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True